let deferredPrompt=null,map=null,selectedMarker=null,selectedLL=null,lastImage=null,lastReport=null;
let heatLayer=null,pinLayer=null,waterLayer=null,osmWaterways=[],lastBboxKey="",forceFallback=false;
const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const W={region:{unknown:0,historic:22,lode:18,glacial:10,greenstone:20,mountain:17,volcanic:14,desert:12,low:-12},landform:{inside:16,bar:14,creek:18,riffle:17,bedrock:22,clay:18,terrace:10,wash:14,lake:-7,upland:-14},bottom:{unknown:0,sand:-8,gravel:8,clay:15,bedrock:22},energy:{high:12,mod:8,flash:10,low:-5,dry:2},panBlack:[0,5,12,18,23],gold:[0,12,28,50,65]};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active");if(b.dataset.tab==="map")setTimeout(()=>{initMap();map.invalidateSize()},100)});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").hidden=false});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;$("installBtn").hidden=true}};

function initMap(){if(map)return;let lat=+$("lat").value||41.084,lon=+$("lon").value||-85.625;map=L.map("mapView").setView([lat,lon],17);
const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);
const satellite=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Tiles © Esri"});
const topo=L.tileLayer("https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",{maxZoom:17,attribution:"© OpenTopoMap"});
L.control.layers({"Street labels":street,"Satellite":satellite,"Topo":topo},null,{collapsed:false}).addTo(map);
heatLayer=L.layerGroup().addTo(map);waterLayer=L.layerGroup().addTo(map);pinLayer=L.layerGroup().addTo(map);
selectedLL=L.latLng(lat,lon);selectedMarker=L.marker(selectedLL,{draggable:true}).addTo(map).bindPopup("Selected analysis point");
selectedMarker.on("dragend",()=>setSelected(selectedMarker.getLatLng(),false));map.on("click",e=>setSelected(e.latlng,true));
renderPins();setStatus("Move map, then tap Refresh Heat Map.");}
function setStatus(t){$("mapStatus").textContent=t;$("hotspotPanel").textContent=t}
function setSelected(ll,open){selectedLL=ll;selectedMarker.setLatLng(ll);$("lat").value=ll.lat.toFixed(6);$("lon").value=ll.lng.toFixed(6);if(open)selectedMarker.openPopup()}
function currentLL(){let lat=+$("lat").value,lon=+$("lon").value;if(isFinite(lat)&&isFinite(lon))return L.latLng(lat,lon);return selectedLL||map.getCenter()}
$("gpsBtn").onclick=()=>{initMap();navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{let ll=L.latLng(p.coords.latitude,p.coords.longitude);$("gpsAccuracy").textContent="±"+Math.round(p.coords.accuracy)+" m";setSelected(ll,false);map.setView(ll,18);setStatus("GPS locked. Tap Refresh Heat Map when ready.")},e=>alert(e.message),{enableHighAccuracy:true,timeout:16000,maximumAge:20000}):alert("GPS unavailable")};
$("refreshHeatBtn").onclick=()=>generateHeatMap();$("clearHeatBtn").onclick=()=>{heatLayer.clearLayers();waterLayer.clearLayers();$("candidateCount").textContent="0";$("bestTarget").textContent="—";setStatus("Heat map cleared. Move map and refresh again.")};
$("toggleFallbackBtn").onclick=()=>{forceFallback=!forceFallback;$("toggleFallbackBtn").textContent=forceFallback?"Fallback ON":"Force fallback";generateHeatMap()};
$("saveCurrentBtn").onclick=()=>save(calc());

function bboxKey(){let b=map.getBounds();return [b.getSouth().toFixed(3),b.getWest().toFixed(3),b.getNorth().toFixed(3),b.getEast().toFixed(3)].join(",")}
async function fetchWaterways(){if(forceFallback)return[];let key=bboxKey();if(key===lastBboxKey&&osmWaterways.length)return osmWaterways;lastBboxKey=key;let b=map.getBounds().pad(.08);
let q=`[out:json][timeout:10];(way["waterway"~"river|stream|creek|brook|canal|ditch"](${b.getSouth()},${b.getWest()},${b.getNorth()},${b.getEast()}););out geom;`;
try{let r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"data="+encodeURIComponent(q)});let d=await r.json();osmWaterways=(d.elements||[]).filter(w=>w.geometry&&w.geometry.length>1).map(w=>({id:w.id,name:w.tags?.name||"mapped waterway",type:w.tags?.waterway||"stream",pts:w.geometry.map(g=>L.latLng(g.lat,g.lon))}));return osmWaterways}catch(e){console.warn(e);return[]}}
async function generateHeatMap(){initMap();heatLayer.clearLayers();waterLayer.clearLayers();$("candidateCount").textContent="loading";$("bestTarget").textContent="loading";setStatus("Building heat map for this exact view. It will stay fixed until you refresh again.");
let ways=await fetchWaterways();let cells=ways.length?riverCells(ways):fallbackCells();drawWaterways(ways);cells.sort((a,b)=>b.score-a.score);drawCells(cells);$("candidateCount").textContent=String(cells.length);$("bestTarget").textContent=cells[0]?`${cells[0].score}/100 ${cells[0].label}`:"No cells";$("hotspotPanel").innerHTML=(ways.length?"<b>River heat map locked to this view.</b>\n":"<b>Fallback heat map.</b> No mapped stream found or fallback forced.\n")+cells.slice(0,8).map((c,i)=>`\n${i+1}. ${c.label} — ${c.score}/100\n${c.reason}`).join("\n");$("mapStatus").textContent=ways.length?"River heat map locked":"Fallback heat map locked"}
function drawWaterways(ways){ways.forEach(w=>L.polyline(w.pts,{color:"#38bdf8",weight:3,opacity:.8}).addTo(waterLayer).bindTooltip(w.name))}
function riverCells(ways){let out=[];ways.forEach(w=>{for(let i=1;i<w.pts.length-1;i+=2){let prev=w.pts[i-1],p=w.pts[i],next=w.pts[i+1];if(!map.getBounds().pad(.05).contains(p))continue;let angle=turn(prev,p,next),curve=clamp(Math.abs(angle)/90*20,0,20),junction=nearJunction(p,w.id),saved=nearSaved(p),score=clamp(Math.round(48+curve+junction+saved.bonus+calBonus()+noise(p.lat,p.lng)*5-2),5,98);let label=Math.abs(angle)>12?"Bend/pay-streak zone":"River gravel zone";let reason=`${w.name} (${w.type}). ${Math.abs(angle)>12?"River curve may form a low-energy heavy-mineral streak.":"Mapped river/creek zone; verify gravel and hard bottom."}${junction?" Confluence nearby.":""}${saved.text?" "+saved.text:""}`;out.push({lat:p.lat,lng:p.lng,score,label,reason,r:map.getZoom()>=18?13:18});if(Math.abs(angle)>10){let br=bearing(prev,next),off=dest(p.lat,p.lng,br+(angle>0?-90:90),22);out.push({lat:off.lat,lng:off.lng,score:clamp(score+5,0,100),label:"Bend-margin edge",reason:"Offset from mapped channel toward likely gravel-bar/pay-streak margin.",r:map.getZoom()>=18?14:19})}}});return dedupe(out)}
function fallbackCells(){let c=currentLL(),out=[];for(let br=0;br<360;br+=30){for(let d=40;d<=180;d+=45){let p=dest(c.lat,c.lng,br,d),s=clamp(Math.round(35+noise(p.lat,p.lng)*25+calBonus()),5,68);out.push({lat:p.lat,lng:p.lng,score:s,label:"Fallback area",reason:"No mapped waterway found. Use only as a rough visual guide.",r:18})}}return out}
function drawCells(cells){cells.forEach(c=>{let color=c.score>=75?"#16a34a":c.score>=58?"#facc15":c.score>=38?"#fb923c":"#ef4444";L.circle([c.lat,c.lng],{radius:c.r,color,fillColor:color,weight:1,opacity:.55,fillOpacity:.32}).addTo(heatLayer).bindPopup(`<b>${c.label}</b><br>Potential: ${c.score}/100<br>${esc(c.reason)}<br><button onclick="selectCell(${c.lat},${c.lng})">Analyze here</button>`)})}
window.selectCell=(lat,lng)=>{let ll=L.latLng(lat,lng);setSelected(ll,false);document.querySelector('[data-tab="analyze"]').click()};
function dedupe(list){let out=[];for(let c of list){if(!out.some(x=>L.latLng(x.lat,x.lng).distanceTo(L.latLng(c.lat,c.lng))<14))out.push(c)}return out}
function turn(a,b,c){let x=bearing(a,b),y=bearing(b,c);return((y-x+540)%360)-180}
function bearing(a,b){let lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,y=Math.sin(dLon)*Math.cos(lat2),x=Math.cos(lat1)*Math.sin(lat2)-Math.sin(lat1)*Math.cos(lat2)*Math.cos(dLon);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function dest(lat,lng,b,feet){let R=6378137,d=feet*.3048,br=b*Math.PI/180,p1=lat*Math.PI/180,l1=lng*Math.PI/180,p2=Math.asin(Math.sin(p1)*Math.cos(d/R)+Math.cos(p1)*Math.sin(d/R)*Math.cos(br)),l2=l1+Math.atan2(Math.sin(br)*Math.sin(d/R)*Math.cos(p1),Math.cos(d/R)-Math.sin(p1)*Math.sin(p2));return{lat:p2*180/Math.PI,lng:l2*180/Math.PI}}
function nearJunction(p,own){let bonus=0;for(let w of osmWaterways){if(w.id===own)continue;for(let q of w.pts){let d=p.distanceTo(q);if(d<45)return 12;if(d<90)bonus=Math.max(bonus,6)}}return bonus}
function noise(lat,lng){let s=Math.sin((lat*127.1+lng*311.7)*1000)*43758.5453;return s-Math.floor(s)}
function calBonus(){let c=JSON.parse(localStorage.goldV6Cal||'{"pans":0,"specks":0}');if(c.pans<5)return 0;return clamp(Math.round(((c.specks/c.pans)-.02)*80),-8,14)}
function nearSaved(ll){let saved=JSON.parse(localStorage.goldV6||"[]").filter(r=>isFinite(r.lat)&&isFinite(r.lon));let bonus=0,text="";saved.forEach(r=>{let d=ll.distanceTo(L.latLng(r.lat,r.lon));if(d<120&&r.score>=70){bonus=Math.max(bonus,8);text="Near previous high-score point."}if(d<80&&(+r.inputs?.gold||0)>=2){bonus=Math.max(bonus,12);text="Near confirmed saved gold."}if(d<60&&r.score<35){bonus=Math.min(bonus,-5);text="Near previous low/no-gold result."}});return{bonus,text}}

$("photo").onchange=e=>{let f=e.target.files[0];if(!f)return;let img=new Image();img.onload=()=>analyzePhoto(img);img.src=URL.createObjectURL(f)};
function analyzePhoto(img){let c=$("photoCanvas"),ctx=c.getContext("2d",{willReadFrequently:true}),scale=Math.min(1000/img.width,1);c.width=img.width*scale;c.height=img.height*scale;ctx.drawImage(img,0,0,c.width,c.height);let d=ctx.getImageData(0,0,c.width,c.height).data,dark=0,gray=0,tan=0,green=0,blue=0,edge=0,total=0,prev=0;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2],lum=.2126*r+.7152*g+.0722*b,max=Math.max(r,g,b),min=Math.min(r,g,b),sat=max?(max-min)/max:0;total++;if(lum<58&&sat<.5)dark++;if(sat<.2&&lum>60&&lum<205)gray++;if(r>85&&g>60&&b<100&&sat>.16)tan++;if(g>r*1.08&&g>b*1.08&&sat>.22)green++;if(b>r*1.08&&b>g*.9&&sat>.18)blue++;if(i>4&&Math.abs(lum-prev)>45)edge++;prev=lum}let pct=x=>x/total;lastImage={texture:clamp((pct(edge)-.075)/.2,0,1),dark:clamp((pct(dark)-.045)/.22,0,1),gravel:clamp((pct(gray)+pct(tan)-.22)/.5,0,1),noise:clamp((pct(green)+pct(blue)-.18)/.45,0,1)};$("photoMetrics").innerHTML=[["Coarse texture",lastImage.texture],["Dark mineral proxy",lastImage.dark],["Gravel/clay proxy",lastImage.gravel],["Vegetation/water interference",lastImage.noise]].map(x=>`<div class="metric"><b>${x[0]}</b><br>${Math.round(x[1]*100)}%</div>`).join("")}
function calc(){let s=0,lines=[];["region","landform","bottom","energy"].forEach(id=>{let val=$(id).value,w=W[id][val];s+=w;lines.push(`${w>=0?"+":""}${w} ${id}: ${val}`)});[["blackSand",16,"black sand"],["heavies",11,"dense heavies"],["coarse",10,"coarse lag"],["obstruction",10,"obstruction"],["tributary",9,"tributary"],["legal",2,"legal checked"]].forEach(a=>{if($(a[0]).checked){s+=a[1];lines.push(`+${a[1]} ${a[2]}`)}});let pb=+$("panBlack").value,g=+$("gold").value,pans=+$("pans").value||0;s+=W.panBlack[pb]+W.gold[g];lines.push(`+${W.panBlack[pb]} pan black sand`);lines.push(`+${W.gold[g]} gold result`);if(pans>=10){s+=7;lines.push("+7 strong sample count")}else if(pans>=5){s+=5;lines.push("+5 useful sample count")}else if(pans>0){s+=2;lines.push("+2 limited sample count")}if(lastImage){let ip=lastImage.texture*7+lastImage.dark*7+lastImage.gravel*5-lastImage.noise*4;s+=ip;lines.push(`${ip>=0?"+":""}${ip.toFixed(1)} photo signal`)}s+=calBonus();s=Math.round(clamp(s,0,100));let conf=(pans>=5||g>=2)?"High":(lastImage||pans>0)?"Medium":"Low",rating=s>=70?"High — systematic testing":s>=50?"Moderate — worth several pans":s>=30?"Low/moderate — quick scout":"Low";$("score").textContent=s;$("rating").textContent=rating;$("barFill").style.width=s+"%";$("confidence").textContent="Confidence: "+conf;$("breakdown").textContent=lines.join("\n");$("recommend").textContent=s>=50?"Pan lowest coarse gravel and follow black sand.":"Move to a stronger river trap.";let ll=currentLL();lastReport={id:String(Date.now()),date:new Date().toISOString(),lat:ll.lat,lon:ll.lng,score:s,rating,confidence:conf,notes:$("notes").value,inputs:collect(),breakdown:lines};return lastReport}
function collect(){return[...document.querySelectorAll("input,select,textarea")].reduce((a,e)=>{if(e.type==="checkbox")a[e.id]=e.checked;else if(e.id)a[e.id]=e.value;return a},{})}
$("calcBtn").onclick=calc;$("saveReportBtn").onclick=()=>save(calc());$("navBtn").onclick=()=>{let ll=currentLL();window.open(`https://maps.apple.com/?ll=${ll.lat},${ll.lng}&q=Gold%20Scout`,"_blank")};
function save(r){let a=JSON.parse(localStorage.goldV6||"[]");a.unshift(r);localStorage.goldV6=JSON.stringify(a.slice(0,1000));renderJournal();renderPins();alert("Saved.")}
function renderPins(){if(!pinLayer)return;pinLayer.clearLayers();JSON.parse(localStorage.goldV6||"[]").filter(r=>isFinite(r.lat)&&isFinite(r.lon)).forEach(r=>{let cls=(+r.inputs?.gold||0)>=2||r.score>=70?"pinSuccess":r.score>=45?"pinMed":"pinLow";L.marker([r.lat,r.lon],{icon:L.divIcon({className:cls,iconSize:[17,17]})}).addTo(pinLayer).bindPopup(`<b>${r.score}/100</b><br>${esc(r.rating)}<br>${esc(r.notes||"")}`)})}
function renderJournal(){let a=JSON.parse(localStorage.goldV6||"[]");$("journalList").innerHTML=a.length?a.map(r=>`<div class="journalItem"><b>${r.score}/100 — ${esc(r.rating)}</b><br>${new Date(r.date).toLocaleString()}<br>${Number(r.lat).toFixed(6)}, ${Number(r.lon).toFixed(6)}<br>${esc(r.notes||"")}</div>`).join(""):"<p>No saved reports yet.</p>"}
$("clearAllBtn").onclick=()=>{if(confirm("Clear all saved?")){localStorage.removeItem("goldV6");renderJournal();renderPins()}};$("exportJsonBtn").onclick=()=>download("gold-scout-v6-4.json",JSON.stringify(JSON.parse(localStorage.goldV6||"[]"),null,2));$("exportCsvBtn").onclick=()=>download("gold-scout-v6-4.csv","date,lat,lon,score,rating,notes\n"+JSON.parse(localStorage.goldV6||"[]").map(r=>[r.date,r.lat,r.lon,r.score,r.rating,r.notes].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv");
function download(n,d,t="application/json"){let b=new Blob([d],{type:t}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
$("addCalBtn").onclick=()=>{let c=JSON.parse(localStorage.goldV6Cal||'{"pans":0,"specks":0}');c.pans+=+$("calPans").value||0;c.specks+=+$("calSpecks").value||0;localStorage.goldV6Cal=JSON.stringify(c);showCal()};$("resetCalBtn").onclick=()=>{localStorage.removeItem("goldV6Cal");showCal()};
function showCal(){let c=JSON.parse(localStorage.goldV6Cal||'{"pans":0,"specks":0}');$("calStatus").textContent=`Calibration: ${c.specks} specks across ${c.pans} pans. Bonus: ${calBonus()}.`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});initMap();renderJournal();showCal();
